# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Box8Home(Sample)' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Box8Home(Sample)
  pod 'Parchment'
  target 'Box8Home(Sample)Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Box8Home(Sample)UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
